name: yunzhou_vpn_desktop
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  grpc: ^3.2.4
  platform_device_id: ^1.0.1
  device_info_plus: ^10.1.0
  network_info_plus: ^5.0.3
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  provider: ^6.1.2
  window_manager: ^0.3.8
  go_router: ^14.0.1
  flutter_hooks: ^0.20.5
  flutter_svg: ^2.0.9
  icons_launcher: ^2.1.7

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/bin/xray_macos/
    - assets/bin/xray_windows/

analyzer:
  plugins:
    - custom_lint

icons_launcher:
  image_path: 'assets/images/icon.png'
  platforms:
    macos:
      enable: true
    windows:
      enable: true
